(require 'color-theme)

(defun color-theme-wdy ()
  "Color theme by User Wdy, created 2013-02-18."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "black")
      (background-mode . dark)
      (background-toolbar-color . "#cf3ccf3ccf3c")
      (border-color . "black")
      (bottom-toolbar-shadow-color . "#79e77df779e7")
      (cursor-color . "green")
      (foreground-color . "#00ff00")
      (mouse-color . "#000000")
      (senator-eldoc-use-color . t)
      (top-toolbar-shadow-color . "#fffffbeeffff")
      (vc-annotate-very-old-color . "#0046FF")
      (viper-saved-cursor-color-in-replace-mode . "Red3"))
     ((display-time-mail-face . mode-line)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . bold)
      (goto-address-url-mouse-face . highlight)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "#00ff00" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "bitstream" :family "Bitstream Vera Sans Mono"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (Info-title-1-face ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (Info-title-2-face ((t (:bold t :weight bold :height 1.44 :family "helv"))))
     (Info-title-3-face ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (Info-title-4-face ((t (:bold t :weight bold :family "helv"))))
     (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     (ac-completion-face ((t (:background "darkblue" :foreground "white"))))
     (ac-etags-candidate-face ((t (:background "gainsboro" :foreground "deep sky blue"))))
     (ac-etags-selection-face ((t (:background "deep sky blue" :foreground "white"))))
     (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     (ac-selection-face ((t (:background "blue" :foreground "white"))))
     (ac-verilog-candidate-face ((t (:background "snow3" :foreground "black"))))
     (ac-verilog-selection-face ((t (:background "SlateBlue3" :foreground "black"))))
     (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     (ahei-hl-line-face ((t (nil))))
     (antlr-font-lock-keyword-face ((t (:bold t :foreground "black" :weight bold))))
     (antlr-font-lock-literal-face ((t (:bold t :foreground "brown4" :weight bold))))
     (antlr-font-lock-ruledef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-ruleref-face ((t (:foreground "blue4"))))
     (antlr-font-lock-tokendef-face ((t (:bold t :foreground "blue" :weight bold))))
     (antlr-font-lock-tokenref-face ((t (:foreground "orange4"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (:background "grey20" :foreground "grey90" :box (:line-width -1 :style released-button)))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (ascii-ascii-face ((t (:background "SkyBlue4"))))
     (ascii-non-ascii-face ((t (:background "darkolivegreen"))))
     (bbdb-company ((t (:italic t :slant italic))))
     (bbdb-field-name ((t (:foreground "lime green"))))
     (bbdb-field-value ((t (:foreground "white"))))
     (bbdb-name ((t (:foreground "lime green" :underline t))))
     (beautiful-blue-face ((t (:foreground "cornflower blue"))))
     (beautiful-blue-red-face ((t (:background "cornflower blue" :foreground "red"))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (black-red-face ((t (:background "red" :foreground "black"))))
     (blank-map-face ((t (:bold t :background "Linen" :foreground "Aquamarine3" :weight bold))))
     (blank-space-face ((t (:background "LightGray"))))
     (blank-tab-face ((t (:background "green" :foreground "black"))))
     (blue ((t (:foreground "blue"))))
     (blue-face ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "green"))))
     (border ((t (:background "black"))))
     (border-glyph ((t (:bold t :weight bold))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "LightSkyBlue"))))
     (button ((t (:underline t))))
     (c-includes-already-face ((t (:foreground "purple"))))
     (c-includes-close-face ((t (:foreground "dark red"))))
     (c-includes-open-face ((t (:foreground "red"))))
     (c-includes-unknown-face ((t (:bold t :foreground "red" :weight bold))))
     (c-nonbreakable-space-face ((t (nil))))
     (calendar-today-face ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "red"))))
     (change-log-acknowledgement-face ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:background "black" :foreground "yellow"))))
     (change-log-conditionals-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-date ((t (:foreground "magenta"))))
     (change-log-date-face ((t (:foreground "RosyBrown"))))
     (change-log-email ((t (:background "black" :foreground "yellow"))))
     (change-log-email-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-file ((t (:background "wheat" :foreground "darkorchid2"))))
     (change-log-file-face ((t (:foreground "Blue"))))
     (change-log-function ((t (:background "black" :foreground "yellow"))))
     (change-log-function-face ((t (:foreground "DarkGoldenrod"))))
     (change-log-list ((t (:background "black" :foreground "cyan"))))
     (change-log-list-face ((t (:foreground "Purple"))))
     (change-log-name ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (change-log-name-face ((t (:foreground "CadetBlue"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (comint-input-face ((t (:foreground "deepskyblue"))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:background "red" :foreground "white"))))
     (compilation-info ((t (:foreground "green"))))
     (compilation-line-number ((t (:background "black" :foreground "yellow"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (nil))))
     (completions-common-part ((t (:foreground "yellow"))))
     (completions-first-difference ((t (:foreground "red"))))
     (cperl-array-face ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
     (cperl-here-face ((t (:foreground "green4"))))
     (cperl-invalid-face ((t (:foreground "white"))))
     (cperl-nonoverridable-face ((t (:foreground "chartreuse3"))))
     (cperl-pod-face ((t (:foreground "brown4"))))
     (cperl-pod-head-face ((t (:foreground "steelblue"))))
     (cscope-file-face ((t (:foreground "blue"))))
     (cscope-function-face ((t (:foreground "magenta"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "green"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-face ((t (nil))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-face ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-comment-tag-face ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-group-tag-face-1 ((t (:foreground "pink" :underline t))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-state-face ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-variable-tag-face ((t (:foreground "light blue" :underline t))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (cvs-filename-face ((t (:foreground "blue4"))))
     (cvs-handled-face ((t (:foreground "pink"))))
     (cvs-header-face ((t (:bold t :foreground "blue4" :weight bold))))
     (cvs-marked-face ((t (:bold t :foreground "green3" :weight bold))))
     (cvs-msg-face ((t (:italic t :slant italic))))
     (cvs-need-action-face ((t (:foreground "orange"))))
     (cvs-unknown-face ((t (:foreground "red"))))
     (cyan ((t (:foreground "cyan"))))
     (cyan-face ((t (:foreground "cyan"))))
     (darkblue-face ((t (:foreground "blue"))))
     (darkcyan-face ((t (:foreground "cyan"))))
     (darkgreen-face ((t (:foreground "green"))))
     (darkmagenta-face ((t (:foreground "magenta"))))
     (darkred-face ((t (:foreground "red"))))
     (darkyellow-face ((t (:foreground "yellow"))))
     (date ((t (:foreground "green"))))
     (diary-face ((t (:foreground "red"))))
     (diff-added ((t (:foreground "aquamarine"))))
     (diff-added-face ((t (nil))))
     (diff-changed ((t (:foreground "deep pink"))))
     (diff-changed-face ((t (nil))))
     (diff-context ((t (:foreground "cornflower blue"))))
     (diff-context-face ((t (:foreground "grey50"))))
     (diff-file-header ((t (:foreground "magenta"))))
     (diff-file-header-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:foreground "green"))))
     (diff-function-face ((t (:foreground "grey50"))))
     (diff-header ((t (:foreground "green"))))
     (diff-header-face ((t (:background "grey85"))))
     (diff-hunk-header ((t (:foreground "OliveDrab1"))))
     (diff-hunk-header-face ((t (:background "grey85"))))
     (diff-index ((t (:foreground "cyan"))))
     (diff-index-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (:background "white" :foreground "red"))))
     (diff-indicator-changed ((t (:foreground "deep pink"))))
     (diff-indicator-removed ((t (:background "red" :foreground "yellow"))))
     (diff-nonexistent ((t (:foreground "magenta"))))
     (diff-nonexistent-face ((t (:bold t :background "grey70" :weight bold))))
     (diff-refine-change ((t (:foreground "dark orchid"))))
     (diff-removed ((t (:foreground "red"))))
     (diff-removed-face ((t (nil))))
     (dired-directory ((t (:background "wheat" :foreground "darkorchid2"))))
     (dired-face-boring ((t (:foreground "RosyBrown"))))
     (dired-face-directory ((t (:foreground "Blue"))))
     (dired-face-executable ((t (:foreground "Green"))))
     (dired-face-flagged ((t (:bold t :foreground "Red" :weight bold))))
     (dired-face-header ((t (:background "grey75" :foreground "black"))))
     (dired-face-marked ((t (:bold t :foreground "Red" :weight bold))))
     (dired-face-permissions ((t (:background "grey75" :foreground "black"))))
     (dired-face-setuid ((t (:foreground "Red"))))
     (dired-face-socket ((t (:foreground "magenta"))))
     (dired-face-symlink ((t (:foreground "Purple"))))
     (dired-flagged ((t (:background "red" :foreground "white"))))
     (dired-header ((t (:foreground "green"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-lis-mode-line-face ((t (:background "darkmagenta" :foreground "white"))))
     (dired-mark ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (dired-marked ((t (:background "red" :foreground "white"))))
     (dired-perm-write ((t (:foreground "chocolate1"))))
     (dired-symlink ((t (:background "black" :foreground "cyan"))))
     (dired-warning ((t (:background "red" :foreground "white"))))
     (diredp-compressed-file-suffix ((t (:foreground "Yellow"))))
     (diredp-date-time ((t (:foreground "goldenrod1"))))
     (diredp-deletion ((t (:background "Red" :foreground "Yellow"))))
     (diredp-deletion-file-name ((t (:foreground "Red"))))
     (diredp-dir-heading ((t (:background "Pink" :foreground "DarkOrchid1"))))
     (diredp-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (diredp-display-msg ((t (:foreground "cornflower blue"))))
     (diredp-exec-priv ((t (:background "LightSteelBlue"))))
     (diredp-executable-tag ((t (:foreground "Red"))))
     (diredp-file-name ((t (:foreground "Blue"))))
     (diredp-file-suffix ((t (:foreground "DarkMagenta"))))
     (diredp-flag-mark ((t (:background "Blueviolet" :foreground "Yellow"))))
     (diredp-flag-mark-line ((t (:background "Skyblue"))))
     (diredp-ignored-file-name ((t (:foreground "#00006DE06DE0"))))
     (diredp-link-priv ((t (:foreground "DarkOrange"))))
     (diredp-no-priv ((t (:background "LightGray"))))
     (diredp-other-priv ((t (:background "PaleGoldenrod"))))
     (diredp-rare-priv ((t (:background "SpringGreen" :foreground "Magenta"))))
     (diredp-read-priv ((t (:background "MediumAquamarine"))))
     (diredp-symlink ((t (:foreground "DarkOrange"))))
     (diredp-write-priv ((t (:background "Orchid"))))
     (display-time-mail-balloon-enhance-face ((t (:background "orange"))))
     (display-time-mail-balloon-gnus-group-face ((t (:foreground "blue"))))
     (display-time-time-balloon-face ((t (:foreground "red"))))
     (doremi-last-face ((t (:stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "bitstream" :family "Bitstream Vera Sans Mono"))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Fixedsys Excelsior 2.00"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Fixedsys Excelsior 2.00"))))
     (ebrowse-default ((t (nil))))
     (ebrowse-default-face ((t (nil))))
     (ebrowse-file-name ((t (:italic t :slant italic))))
     (ebrowse-file-name-face ((t (:italic t :slant italic))))
     (ebrowse-member-attribute ((t (:foreground "red1"))))
     (ebrowse-member-attribute-face ((t (:foreground "red"))))
     (ebrowse-member-class ((t (:foreground "purple"))))
     (ebrowse-member-class-face ((t (:foreground "purple"))))
     (ebrowse-progress ((t (:background "blue1"))))
     (ebrowse-progress-face ((t (:background "blue"))))
     (ebrowse-root-class ((t (:bold t :foreground "blue1" :weight bold))))
     (ebrowse-root-class-face ((t (:bold t :foreground "blue" :weight bold))))
     (ebrowse-tree-mark ((t (:foreground "red1"))))
     (ebrowse-tree-mark-face ((t (:foreground "red"))))
     (ecb-bucket-token-face ((t (:bold t :weight bold))))
     (ecb-default-general-face ((t (:height 1.0))))
     (ecb-default-highlight-face ((t (:background "magenta" :height 1.0))))
     (ecb-directories-general-face ((t (:height 0.9))))
     (ecb-directory-face ((t (:background "Cyan4"))))
     (ecb-history-face ((t (:background "Cyan4"))))
     (ecb-history-general-face ((t (:height 0.9))))
     (ecb-method-face ((t (:background "Cyan4" :slant normal :weight normal))))
     (ecb-methods-general-face ((t (:slant normal))))
     (ecb-source-face ((t (:background "Cyan4"))))
     (ecb-source-in-directories-buffer-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-face ((t (:foreground "LightBlue1"))))
     (ecb-sources-general-face ((t (:height 0.9))))
     (ecb-token-header-face ((t (:background "Steelblue4"))))
     (ecb-type-token-class-face ((t (:bold t :weight bold))))
     (ecb-type-token-enum-face ((t (:bold t :weight bold))))
     (ecb-type-token-group-face ((t (:bold t :foreground "dim gray" :weight bold))))
     (ecb-type-token-interface-face ((t (:bold t :weight bold))))
     (ecb-type-token-struct-face ((t (:bold t :weight bold))))
     (ecb-type-token-typedef-face ((t (:bold t :weight bold))))
     (edb-inter-field-face ((t (:foreground "deep sky blue"))))
     (edb-normal-summary-face ((t (:foreground "gold"))))
     (ediff-current-diff-A ((t (:background "DarkSeaGreen3" :foreground "blue violet"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "DodgerBlue1" :foreground "gray11"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-current-diff-face-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-face-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-face-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-face-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-face-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-face-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "gold1" :foreground "red"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "chocolate2" :foreground "dark slate blue"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-fine-diff-face-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-face-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-face-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-face-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-face-Ancestor ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-face-C ((t (:background "Grey" :foreground "White"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:foreground "green" :weight normal))))
     (emacs-wiki-bad-link-face ((t (:bold t :foreground "coral" :underline "coral" :weight bold))))
     (emacs-wiki-link-face ((t (:bold t :foreground "cyan" :underline "cyan" :weight bold))))
     (erb-comment-delim-face ((t (:bold t :background "snow3" :foreground "darkgreen" :weight bold))))
     (erb-comment-face ((t (:bold t :background "snow2" :foreground "darkgreen" :weight bold))))
     (erb-delim-face ((t (:background "snow3"))))
     (erb-exec-delim-face ((t (:bold t :background "snow3" :weight bold))))
     (erb-exec-face ((t (:background "snow2"))))
     (erb-face ((t (:background "snow2"))))
     (erb-out-delim-face ((t (:bold t :background "snow3" :foreground "darkred" :weight bold))))
     (erb-out-face ((t (:background "snow2"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-current-nick-face ((t (:bold t :foreground "yellow" :weight bold))))
     (erc-dangerous-host-face ((t (:foreground "red"))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:background "Red" :foreground "White"))))
     (erc-fool-face ((t (:foreground "Gray85"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-host-danger-face ((t (:foreground "red"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-keyword-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-timestamp-face ((t (:bold t :foreground "green" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "Orchid" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "blue" :weight bold))))
     (eshell-ls-directory-face ((t (:bold t :foreground "green" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "orange" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "LightSalmon"))))
     (eshell-ls-readonly-face ((t (:foreground "gray"))))
     (eshell-ls-special-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (eshell-ls-text-face ((t (:foreground "medium aquamarine"))))
     (eshell-ls-todo-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-unreadable-face ((t (:foreground "DarkGrey"))))
     (eshell-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (eshell-test-failed-face ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (eshell-test-ok-face ((t (:bold t :foreground "Green" :weight bold))))
     (excerpt ((t (:italic t :slant italic))))
     (face-1 ((t (:stipple nil :foreground "royal blue" :family "andale mono"))))
     (face-2 ((t (:stipple nil :foreground "DeepSkyBlue1" :overline nil :underline nil :slant normal :foundry "outline" :family "andale mono"))))
     (face-3 ((t (:stipple nil :foreground "NavajoWhite3"))))
     (ff-paths-non-existant-file-face ((t (:bold t :foreground "NavyBlue" :weight bold))))
     (ffap ((t (:background "blue" :foreground "red"))))
     (fg:black ((t (:foreground "black"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cyan"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-latex-bold-face ((t (nil))))
     (font-latex-italic-face ((t (nil))))
     (font-latex-math-face ((t (nil))))
     (font-latex-sedate-face ((t (:foreground "Gray85"))))
     (font-latex-string-face ((t (:foreground "orange"))))
     (font-latex-warning-face ((t (:bold t :foreground "gold" :weight bold))))
     (font-lock-builtin-face ((t (:foreground "magenta"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "deeppink"))))
     (font-lock-constant-face ((t (:foreground "blue"))))
     (font-lock-doc-face ((t (:foreground "cyan"))))
     (font-lock-doc-string-face ((t (:foreground "cyan"))))
     (font-lock-emphasized-face ((t (:bold t :background "lightyellow2" :weight bold))))
     (font-lock-exit-face ((t (:foreground "green"))))
     (font-lock-function-name-face ((t (:foreground "purple"))))
     (font-lock-keyword-face ((t (:foreground "red"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-other-emphasized-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-other-type-face ((t (:bold t :foreground "gold1" :weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "blue1"))))
     (font-lock-reference-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "red"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "yellow"))))
     (font-lock-special-comment-face ((t (:foreground "blue4"))))
     (font-lock-special-keyword-face ((t (:foreground "red4"))))
     (font-lock-string-face ((t (:foreground "cyan"))))
     (font-lock-type-face ((t (:foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "violet"))))
     (font-lock-warning-face ((t (:bold t :foreground "red" :weight bold))))
     (fringe ((t (:background "gray16" :foreground "#00ff00"))))
     (gdb-arrow-face ((t (:bold t :background "yellow" :foreground "red" :weight bold))))
     (gnus-cite-attribution-face ((t (:italic t :slant italic))))
     (gnus-cite-face-1 ((t (:bold t :foreground "deep sky blue" :weight bold))))
     (gnus-cite-face-10 ((t (:foreground "medium purple"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:bold t :foreground "cyan" :weight bold))))
     (gnus-cite-face-3 ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-cite-face-4 ((t (:foreground "light pink"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:bold t :foreground "chocolate" :weight bold))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-cite-face-list ((t (:bold t :foreground "red" :weight bold))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-filterhist-face-1 ((t (nil))))
     (gnus-group-mail-1-empty-face ((t (:foreground "aquamarine1"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "aquamarine1" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "aquamarine3"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "aquamarine3" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "aquamarine4"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "aquamarine4" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3-empty-face ((t (nil))))
     (gnus-group-news-3-face ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "DarkTurquoise"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "forest green" :slant italic))))
     (gnus-header-from-face ((t (:bold t :foreground "spring green" :weight bold))))
     (gnus-header-name-face ((t (:foreground "deep sky blue"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "purple" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "orange" :weight bold))))
     (gnus-picon-face ((t (:background "white" :foreground "black"))))
     (gnus-picon-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-face ((t (:background "white" :foreground "black"))))
     (gnus-picons-xbm-face ((t (:background "white" :foreground "black"))))
     (gnus-signature-face ((t (:bold t :foreground "khaki" :weight bold))))
     (gnus-splash ((t (:foreground "Brown"))))
     (gnus-splash-face ((t (:foreground "Brown"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "pink" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "PaleGreen" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "pink" :slant italic))))
     (gnus-summary-low-unread-face ((t (:italic t :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (gnus-x-face ((t (:background "white" :foreground "black"))))
     (green ((t (:foreground "green"))))
     (green-face ((t (:foreground "green"))))
     (green-red-face ((t (:background "red" :foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "Gray"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :foreground "green" :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "helv"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue" :weight bold))))
     (hi-green ((t (:background "green"))))
     (hi-green-b ((t (:bold t :foreground "green" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red" :weight bold))))
     (hi-yellow ((t (:background "yellow"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-changes-delete-face ((t (:foreground "red" :underline t))))
     (highlight-changes-face ((t (:foreground "red"))))
     (highline-face ((t (:background "gray35" :foreground "white"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (hl-line ((t (:background "blue" :foreground "red"))))
     (hl-line-face ((t (:background "#30FF30FF30FF" :inverse-video nil :underline t))))
     (hl-paren-face ((t (nil))))
     (holiday-face ((t (:background "pink"))))
     (horizontal-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (hproperty:but-face ((t (:bold t :background "wheat" :foreground "medium violet red" :weight bold))))
     (hproperty:flash-face ((t (:bold t :background "wheat" :foreground "gray80" :weight bold))))
     (hproperty:highlight-face ((t (:bold t :background "wheat" :foreground "red" :weight bold))))
     (hproperty:item-face ((t (:bold t :weight bold))))
     (html-helper-bold-face ((t (:bold t :weight bold))))
     (html-helper-bold-italic-face ((t (nil))))
     (html-helper-builtin-face ((t (:foreground "blue3" :underline t))))
     (html-helper-italic-face ((t (:bold t :foreground "yellow" :weight bold))))
     (html-helper-underline-face ((t (:underline t))))
     (html-tag-face ((t (:foreground "Blue"))))
     (hyper-apropos-documentation ((t (:foreground "white"))))
     (hyper-apropos-heading ((t (:bold t :weight bold))))
     (hyper-apropos-hyperlink ((t (:foreground "sky blue"))))
     (hyper-apropos-major-heading ((t (:bold t :weight bold))))
     (hyper-apropos-section-heading ((t (:bold t :weight bold))))
     (hyper-apropos-warning ((t (:bold t :foreground "red" :weight bold))))
     (ibuffer-deletion-face ((t (nil))))
     (ibuffer-marked-face ((t (:foreground "red"))))
     (icicle-Completions-instruction-1 ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-Completions-instruction-2 ((t (:foreground "#0000D53CD53C"))))
     (icicle-candidate-part ((t (:background "#451700143197"))))
     (icicle-common-match-highlight-Completions ((t (:foreground "#2017A71F2017"))))
     (icicle-complete-input ((t (:foreground "#B19E6A64B19E"))))
     (icicle-completion ((t (:foreground "#0000D53CD53C"))))
     (icicle-current-candidate-highlight ((t (:background "#69D40A460000"))))
     (icicle-extra-candidate ((t (:background "#4517305D0000"))))
     (icicle-historical-candidate ((t (:foreground "#DBD599DF0000"))))
     (icicle-input-completion-fail ((t (:background "#22225F5F2222"))))
     (icicle-input-completion-fail-lax ((t (:background "#00005E3B5A8D"))))
     (icicle-match-highlight-Completions ((t (:foreground "#1F1FA21CA21C"))))
     (icicle-match-highlight-minibuffer ((t (:underline t))))
     (icicle-mode-line-help ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-multi-command-completion ((t (:background "#8B3500007533" :foreground "#0000D53CD53C"))))
     (icicle-mustmatch-completion ((t (:box (:line-width 2 :color "Blue")))))
     (icicle-proxy-candidate ((t (:background "#316B22970000"))))
     (icicle-saved-candidate ((t (:background "gray20"))))
     (icicle-search-context-level-1 ((t (:background "#FA6CC847FFFF"))))
     (icicle-search-context-level-2 ((t (:background "#C847FFFFE423"))))
     (icicle-search-context-level-3 ((t (:background "#C847D8FEFFFF"))))
     (icicle-search-context-level-4 ((t (:background "#EF46FFFFC847"))))
     (icicle-search-context-level-5 ((t (:background "#FCFCE1E1FFFF"))))
     (icicle-search-context-level-6 ((t (:background "#E1E1FFFFF0F0"))))
     (icicle-search-context-level-7 ((t (:background "#E1E1EAEAFFFF"))))
     (icicle-search-context-level-8 ((t (:background "#F6F5FFFFE1E1"))))
     (icicle-search-current-input ((t (:background "#7F0D00007F0D" :foreground "White"))))
     (icicle-search-main-regexp-current ((t (:background "#00004AA652F1"))))
     (icicle-search-main-regexp-others ((t (:background "#348608690000"))))
     (icicle-special-candidate ((t (:background "#176900004E0A"))))
     (icicle-whitespace-highlight ((t (:background "#000093F402A2"))))
     (icompletep-choices ((t (:foreground "yellow"))))
     (icompletep-determined ((t (:foreground "green"))))
     (icompletep-keys ((t (:foreground "Red"))))
     (icompletep-nb-candidates ((t (:foreground "green"))))
     (idlwave-help-link-face ((t (:foreground "Blue"))))
     (idlwave-shell-bp-face ((t (:background "Pink" :foreground "Black"))))
     (ido-first-match ((t (:foreground "yellow" :weight normal))))
     (ido-first-match-face ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:background "red" :foreground "white"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "green" :weight normal))))
     (ido-only-match-face ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-subdir-face ((t (:foreground "MediumSlateBlue"))))
     (ifdef-highlight-face1 ((t (:background "paleturquoise4"))))
     (ifdef-highlight-face2 ((t (:background "paleGreen3"))))
     (ifdef-highlight-face3 ((t (:background "yellow4"))))
     (ifdef-highlight-face4 ((t (:background "pink4"))))
     (info-command-ref-item ((t (:background "LightGray" :foreground "Blue"))))
     (info-file ((t (:background "LightGray" :foreground "Blue"))))
     (info-function-ref-item ((t (:background "LightGray" :foreground "deeppink1"))))
     (info-header-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-header-xref ((t (:bold t :foreground "magenta4" :weight bold))))
     (info-macro-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-menu ((t (:foreground "Blue"))))
     (info-menu-5 ((t (:foreground "gold" :underline t))))
     (info-menu-6 ((t (nil))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-menu-star ((t (:background "yellow" :foreground "red"))))
     (info-node ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (info-quoted-name ((t (:foreground "cornflower blue"))))
     (info-reference-item ((t (:background "white" :foreground "cornflower blue"))))
     (info-single-quote ((t (:background "red" :foreground "white"))))
     (info-special-form-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-string ((t (:foreground "magenta"))))
     (info-syntax-class-item ((t (:background "LightGray" :foreground "DarkGreen"))))
     (info-title-1 ((t (:foreground "yellow"))))
     (info-title-2 ((t (:foreground "lightblue"))))
     (info-title-3 ((t (:foreground "violetred1"))))
     (info-title-4 ((t (:foreground "green"))))
     (info-user-option-ref-item ((t (:background "LightGray" :foreground "Red"))))
     (info-variable-ref-item ((t (:background "LightGray" :foreground "FireBrick"))))
     (info-xref ((t (:bold t :foreground "yellow" :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (ispell-face ((t (:bold t :background "#3454b4" :foreground "yellow" :weight bold))))
     (italic ((t (:italic t :slant italic))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-db-active-breakpoint-face ((t (:background "red" :foreground "black"))))
     (jde-db-requested-breakpoint-face ((t (:background "yellow" :foreground "black"))))
     (jde-db-spec-breakpoint-face ((t (:background "green" :foreground "black"))))
     (jde-java-font-lock-api-face ((t (:foreground "dark goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "CadetBlue"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "green4"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "cadetblue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "Orchid"))))
     (jde-java-font-lock-number-face ((t (:foreground "RosyBrown"))))
     (jde-java-font-lock-operator-face ((t (:foreground "medium blue"))))
     (jde-java-font-lock-package-face ((t (:foreground "blue3"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (js2-error-face ((t (:foreground "red"))))
     (js2-external-variable-face ((t (:foreground "orange"))))
     (js2-function-param-face ((t (:foreground "SeaGreen"))))
     (js2-instance-member-face ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter-face ((t (:foreground "green"))))
     (js2-jsdoc-html-tag-name-face ((t (:foreground "yellow"))))
     (js2-jsdoc-tag-face ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type-face ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value-face ((t (:foreground "PeachPuff3"))))
     (js2-magic-paren-face ((t (:underline t))))
     (js2-private-function-call-face ((t (:foreground "goldenrod"))))
     (js2-private-member-face ((t (:foreground "PeachPuff3"))))
     (js2-warning-face ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (lazy-highlight-face ((t (:bold t :foreground "dark magenta" :weight bold))))
     (left-margin ((t (:background "darkblue" :foreground "yellow"))))
     (light-blue-face ((t (:foreground "cornflower blue"))))
     (lightblue-face ((t (:foreground "cornflower blue"))))
     (linemenu-face ((t (:background "gray30"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linkd-command ((t (:foreground "red" :underline t))))
     (linkd-generic-link ((t (:foreground "blue"))))
     (linkd-generic-link-name ((t (:foreground "blue"))))
     (linkd-icon ((t (:underline nil))))
     (linkd-star ((t (:foreground "#ffffff"))))
     (linkd-star-name ((t (:background "Pink" :foreground "blue"))))
     (linkd-tag ((t (:foreground "#ffffff"))))
     (linkd-tag-name ((t (:foreground "blue" :underline t))))
     (linkd-wiki ((t (:foreground "FireBrick" :underline t))))
     (linum ((t (:foreground "cyan"))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "dark green"))))
     (log-view-file ((t (:bold t :weight bold))))
     (log-view-file-face ((t (:bold t :background "grey70" :weight bold))))
     (log-view-message ((t (:bold t :weight bold))))
     (log-view-message-face ((t (:background "grey85"))))
     (m4-face ((t (:background "gray90" :foreground "orange3"))))
     (magenta ((t (:foreground "magenta"))))
     (magenta-face ((t (:foreground "magenta"))))
     (makefile-makepp-perl ((t (:background "DarkBlue"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (makefile-targets ((t (:background "wheat" :foreground "darkorchid2"))))
     (man-bold ((t (:bold t :weight bold))))
     (man-heading ((t (:bold t :weight bold))))
     (man-italic ((t (:foreground "yellow"))))
     (man-xref ((t (:underline t))))
     (match ((t (:background "RoyalBlue3" :foreground "cyan"))))
     (menu ((t (:background "gray16" :foreground "green"))))
     (message-cited-text ((t (:bold t :foreground "red" :weight bold))))
     (message-header-cc ((t (:bold t :foreground "green4" :weight bold))))
     (message-header-contents ((t (:foreground "white"))))
     (message-header-name ((t (:bold t :foreground "orange" :weight bold))))
     (message-header-newsgroups ((t (:bold t :foreground "violet" :weight bold))))
     (message-header-other ((t (:bold t :foreground "chocolate" :weight bold))))
     (message-header-subject ((t (:bold t :foreground "yellow" :weight bold))))
     (message-header-to ((t (:bold t :foreground "cyan" :weight bold))))
     (message-header-xheader ((t (:bold t :foreground "light blue" :weight bold))))
     (message-headers ((t (:bold t :foreground "orange" :weight bold))))
     (message-highlighted-header-contents ((t (:bold t :weight bold))))
     (message-mml ((t (:bold t :background "Green3" :weight bold))))
     (message-separator ((t (:foreground "blue3"))))
     (message-url ((t (:bold t :foreground "pink" :weight bold))))
     (minibuffer-prompt ((t (:foreground "dark blue"))))
     (mmm-default-submode-face ((t (:background "#c0c0c5"))))
     (mmm-face ((t (:background "black" :foreground "green"))))
     (moccur-current-line-face ((t (:background "blue" :foreground "red" :underline t))))
     (moccur-face ((t (:background "white" :foreground "red" :weight normal))))
     (mode-line ((t (:background "gray16" :foreground "#00ff00" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:background "gray16" :foreground "#00ff00"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:italic t :background "white" :foreground "cadetblue" :box (:line-width -1 :color "grey75") :overline "red" :underline "red" :slant oblique :weight light))))
     (mode-line-lines-face ((t (:background "dark slate blue" :foreground "yellow"))))
     (modeline-mousable ((t (:background "gray16" :foreground "#00ff00"))))
     (modeline-mousable-minor-mode ((t (:background "gray16" :foreground "#00ff00"))))
     (mouse ((t (:background "yellow"))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "yellow"))))
     (mpg123-face-slider ((t (:background "yellow" :foreground "black"))))
     (my-summary-highlight-face ((t (:foreground "White"))))
     (my-tab-face ((t (:background "SlateBlue1"))))
     (my-url-face ((t (:foreground "PaleTurquoise"))))
     (next-error ((t (:background "#4CAA4CAA4CAA"))))
     (nil ((t (nil))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (overlay-empty-face ((t (nil))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:bold t :foreground "salmon" :weight bold))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-blink-off ((t (:foreground "gray80"))))
     (paren-blink-on ((t (:foreground "purple"))))
     (paren-face ((t (:background "lightgoldenrod"))))
     (paren-face-match ((t (:background "turquoise"))))
     (paren-face-mismatch ((t (:background "purple" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (paren-match ((t (:background "dark blue"))))
     (paren-mismatch ((t (:background "DeepPink" :foreground "LightSkyBlue"))))
     (paren-mismatch-face ((t (:background "DeepPink" :foreground "white"))))
     (paren-no-match-face ((t (:background "yellow" :foreground "white"))))
     (pointer ((t (:foreground "White"))))
     (primary-selection ((t (:background "#00ff00" :foreground "black"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "blue" :foreground "red"))))
     (reb-match-0 ((t (:background "lightblue"))))
     (reb-match-1 ((t (:background "aquamarine"))))
     (reb-match-2 ((t (:background "springgreen"))))
     (reb-match-3 ((t (:background "yellow"))))
     (red ((t (:foreground "red"))))
     (red-blue-face ((t (:background "blue" :foreground "red"))))
     (red-face ((t (:foreground "red"))))
     (red-yellow-face ((t (:background "yellow" :foreground "red"))))
     (region ((t (:background "steelblue" :foreground "white"))))
     (right-margin ((t (:background "darkblue" :foreground "yellow"))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "yellow"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (rpm-spec-var-face ((t (:foreground "maroon"))))
     (ruler-mode-column-number-face ((t (:stipple nil :background "grey76" :foreground "black" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-current-column-face ((t (:bold t :stipple nil :background "grey76" :foreground "yellow" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight bold :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-default-face ((t (:stipple nil :background "grey76" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-fill-column-face ((t (:stipple nil :background "grey76" :foreground "red" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-margins-face ((t (:stipple nil :background "grey64" :foreground "grey64" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (ruler-mode-tab-stop-face ((t (:stipple nil :background "grey76" :foreground "steelblue" :inverse-video nil :box (:color "grey76" :line-width 1 :style released-button) :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "outline" :family "andale mono"))))
     (scroll-bar ((t (:background "gray16" :foreground "#00ff00"))))
     (search-buffers-face ((t (:bold t :background "SkyBlue" :foreground "Black" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "gray20" :foreground "azure3" :weight bold))))
     (searchm-buffer ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (searchm-button ((t (:bold t :background "CadetBlue" :foreground "white" :weight bold))))
     (searchm-field ((t (:background "grey89"))))
     (searchm-field-label ((t (:bold t :weight bold))))
     (searchm-highlight ((t (:bold t :background "darkseagreen2" :foreground "black" :weight bold))))
     (secondary-selection ((t (:background "#00ff00" :foreground "black"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-intangible-face ((t (:foreground "gray25"))))
     (semantic-read-only-face ((t (:background "gray25"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray25"))))
     (senator-momentary-highlight-face ((t (:background "gray70"))))
     (senator-read-only-face ((t (:background "#CCBBBB"))))
     (setnu-line-number-face ((t (:bold t :background "Grey15" :foreground "White" :weight bold))))
     (sgml-comment-face ((t (:italic t :foreground "SeaGreen" :slant italic))))
     (sgml-doctype-face ((t (:foreground "orange"))))
     (sgml-end-tag-face ((t (:foreground "greenyellow"))))
     (sgml-entity-face ((t (:foreground "gold"))))
     (sgml-ignored-face ((t (:background "gray60" :foreground "gray20"))))
     (sgml-ms-end-face ((t (:foreground "green"))))
     (sgml-ms-start-face ((t (:foreground "yellow"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sgml-pi-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-sgml-face ((t (:foreground "yellow"))))
     (sgml-short-ref-face ((t (:foreground "deep sky blue"))))
     (sgml-shortref-face ((t (:bold t :foreground "gray40" :weight bold))))
     (sgml-start-tag-face ((t (:foreground "mediumspringgreen"))))
     (sh-escaped-newline ((t (:foreground "magenta"))))
     (sh-heredoc ((t (:foreground "deeppink"))))
     (sh-heredoc-face ((t (:foreground "tan"))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (shell-input-face ((t (:bold t :background "wheat" :foreground "blue" :weight bold))))
     (shell-option-face ((t (:foreground "blue4"))))
     (shell-output-2-face ((t (:foreground "green4"))))
     (shell-output-3-face ((t (:foreground "green4"))))
     (shell-output-face ((t (:bold t :weight bold))))
     (shell-prompt-face ((t (:foreground "red4"))))
     (show-paren-match ((t (:background "magenta" :foreground "yellow"))))
     (show-paren-match-face ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
     (show-paren-mismatch-face ((t (:background "purple" :foreground "white"))))
     (show-tabs-space ((t (:background "yellow1"))))
     (show-tabs-space-face ((t (:foreground "yellow"))))
     (show-tabs-tab ((t (:background "red1"))))
     (show-tabs-tab-face ((t (:foreground "red"))))
     (smerge-base-face ((t (:foreground "red"))))
     (smerge-markers-face ((t (:background "grey85"))))
     (smerge-mine-face ((t (:foreground "blue"))))
     (smerge-other-face ((t (:foreground "darkgreen"))))
     (special-string-face ((t (:foreground "light green"))))
     (speedbar-button-face ((t (:foreground "#00ff00"))))
     (speedbar-directory-face ((t (:foreground "#00ff00"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "#00ff00" :foreground "purple"))))
     (speedbar-selected-face ((t (:foreground "deeppink" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (strokes-char-face ((t (:background "lightgray"))))
     (svn-status-directory-face ((t (:foreground "lightskyblue1"))))
     (svn-status-filename-face ((t (:foreground "yellow"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "palegreen2"))))
     (svn-status-marked-popup-face ((t (:foreground "palegreen2"))))
     (svn-status-switched-face ((t (:foreground "Aquamarine"))))
     (svn-status-update-available-face ((t (:foreground "yellow"))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (template-message-face ((t (:bold t :weight bold))))
     (term-black ((t (:foreground "black"))))
     (term-blackbg ((t (:background "black"))))
     (term-blue ((t (:foreground "#4186be"))))
     (term-blue-bold-face ((t (:bold t :background "snow2" :foreground "blue" :weight bold))))
     (term-blue-face ((t (:foreground "blue"))))
     (term-blue-inv-face ((t (:background "blue"))))
     (term-blue-ul-face ((t (:background "snow2" :foreground "blue" :underline t))))
     (term-bluebg ((t (:background "#4186be"))))
     (term-bold ((t (:bold t :weight bold))))
     (term-cyan ((t (:foreground "#71bebe"))))
     (term-cyan-bold-face ((t (:bold t :background "snow2" :foreground "cyan" :weight bold))))
     (term-cyan-face ((t (:foreground "cyan"))))
     (term-cyan-inv-face ((t (:background "cyan"))))
     (term-cyan-ul-face ((t (:background "snow2" :foreground "cyan" :underline t))))
     (term-cyanbg ((t (:background "#71bebe"))))
     (term-default ((t (:stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "adobe" :family "courier"))))
     (term-default-bg ((t (nil))))
     (term-default-bg-inv ((t (nil))))
     (term-default-bold-face ((t (:bold t :background "snow2" :foreground "darkslategray" :weight bold))))
     (term-default-face ((t (:background "snow2" :foreground "darkslategray"))))
     (term-default-fg ((t (nil))))
     (term-default-fg-inv ((t (nil))))
     (term-default-inv-face ((t (:background "darkslategray" :foreground "snow2"))))
     (term-default-ul-face ((t (:background "snow2" :foreground "darkslategray" :underline t))))
     (term-green ((t (:foreground "#e5f779"))))
     (term-green-bold-face ((t (:bold t :background "snow2" :foreground "green" :weight bold))))
     (term-green-face ((t (:foreground "green"))))
     (term-green-inv-face ((t (:background "green"))))
     (term-green-ul-face ((t (:background "snow2" :foreground "green" :underline t))))
     (term-greenbg ((t (:background "#e5f779"))))
     (term-invisible ((t (nil))))
     (term-invisible-inv ((t (nil))))
     (term-magenta ((t (:foreground "#ef9ebe"))))
     (term-magenta-bold-face ((t (:bold t :background "snow2" :foreground "magenta" :weight bold))))
     (term-magenta-face ((t (:foreground "magenta"))))
     (term-magenta-inv-face ((t (:background "magenta"))))
     (term-magenta-ul-face ((t (:background "snow2" :foreground "magenta" :underline t))))
     (term-magentabg ((t (:background "#ef9ebe"))))
     (term-red ((t (:foreground "#ef8171"))))
     (term-red-bold-face ((t (:bold t :background "snow2" :foreground "red" :weight bold))))
     (term-red-face ((t (:foreground "red"))))
     (term-red-inv-face ((t (:background "red"))))
     (term-red-ul-face ((t (:background "snow2" :foreground "red" :underline t))))
     (term-redbg ((t (:background "#ef8171"))))
     (term-underline ((t (:underline t))))
     (term-white ((t (:foreground "#c0c0c0"))))
     (term-white-bold-face ((t (:bold t :background "snow2" :foreground "white" :weight bold))))
     (term-white-face ((t (:foreground "white"))))
     (term-white-inv-face ((t (:background "snow2"))))
     (term-white-ul-face ((t (:background "snow2" :foreground "white" :underline t))))
     (term-whitebg ((t (:background "#c0c0c0"))))
     (term-yellow ((t (:foreground "#fff796"))))
     (term-yellow-bold-face ((t (:bold t :background "snow2" :foreground "yellow" :weight bold))))
     (term-yellow-face ((t (:foreground "yellow"))))
     (term-yellow-inv-face ((t (:background "yellow"))))
     (term-yellow-ul-face ((t (:background "snow2" :foreground "yellow" :underline t))))
     (term-yellowbg ((t (:background "#fff796"))))
     (tex-math-face ((t (:foreground "RosyBrown"))))
     (texinfo-heading-face ((t (:foreground "Blue"))))
     (text-cursor ((t (:background "Red3" :foreground "black"))))
     (tool-bar ((t (:background "gray16" :foreground "green" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "gray16" :foreground "#00ff00"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
     (underline-face ((t (:underline t))))
     (underline-green-face ((t (:foreground "green" :underline t))))
     (variable-pitch ((t (:family "helv"))))
     (vc-annotate-face-0046FF ((t (:background "black" :foreground "wheat"))))
     (vcursor ((t (:background "cyan" :foreground "blue" :underline t))))
     (vertical-border ((t (nil))))
     (vertical-divider ((t (:background "gray16" :foreground "#00ff00"))))
     (vhdl-font-lock-attribute-face ((t (:foreground "Orchid"))))
     (vhdl-font-lock-directive-face ((t (:foreground "CadetBlue"))))
     (vhdl-font-lock-enumvalue-face ((t (:foreground "Gold4"))))
     (vhdl-font-lock-function-face ((t (:foreground "Orchid4"))))
     (vhdl-font-lock-generic-/constant-face ((t (:foreground "Gold3"))))
     (vhdl-font-lock-prompt-face ((t (:bold t :foreground "Red" :weight bold))))
     (vhdl-font-lock-reserved-words-face ((t (:bold t :foreground "Orange" :weight bold))))
     (vhdl-font-lock-translate-off-face ((t (:background "LightGray"))))
     (vhdl-font-lock-type-face ((t (:foreground "ForestGreen"))))
     (vhdl-font-lock-variable-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-architecture-face ((t (:foreground "Blue"))))
     (vhdl-speedbar-architecture-selected-face ((t (:foreground "Blue" :underline t))))
     (vhdl-speedbar-configuration-face ((t (:foreground "DarkGoldenrod"))))
     (vhdl-speedbar-configuration-selected-face ((t (:foreground "DarkGoldenrod" :underline t))))
     (vhdl-speedbar-entity-face ((t (:foreground "ForestGreen"))))
     (vhdl-speedbar-entity-selected-face ((t (:foreground "ForestGreen" :underline t))))
     (vhdl-speedbar-instantiation-face ((t (:foreground "Brown"))))
     (vhdl-speedbar-instantiation-selected-face ((t (:foreground "Brown" :underline t))))
     (vhdl-speedbar-package-face ((t (:foreground "Grey50"))))
     (vhdl-speedbar-package-selected-face ((t (:foreground "Grey50" :underline t))))
     (vhdl-speedbar-subprogram-face ((t (:foreground "Orchid4"))))
     (view-mode-mode-line-face ((t (:background "red" :foreground "white"))))
     (viper-minibuffer-emacs-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-minibuffer-insert-face ((t (:background "pink" :foreground "Black"))))
     (viper-minibuffer-vi-face ((t (:background "grey" :foreground "DarkGreen"))))
     (viper-replace-overlay-face ((t (:background "darkseagreen2" :foreground "Black"))))
     (viper-search-face ((t (:background "khaki" :foreground "Black"))))
     (vm-header-content-face ((t (:italic t :foreground "gray80" :slant italic))))
     (vm-header-from-face ((t (:italic t :background "#65889C" :foreground "cyan" :slant italic))))
     (vm-header-name-face ((t (:foreground "cyan"))))
     (vm-header-subject-face ((t (:foreground "cyan"))))
     (vm-header-to-face ((t (:italic t :foreground "cyan" :slant italic))))
     (vm-message-cited-face ((t (:foreground "Gray80"))))
     (vm-monochrome-image ((t (:background "white" :foreground "gray30"))))
     (vm-summary-face-1 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-2 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-3 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-face-4 ((t (:foreground "MediumAquamarine"))))
     (vm-summary-highlight-face ((t (:foreground "White"))))
     (vm-xface ((t (:background "white" :foreground "black"))))
     (vmpc-pre-sig-face ((t (:foreground "forestgreen"))))
     (vmpc-sig-face ((t (:foreground "steelblue"))))
     (vvb-face ((t (:background "pink" :foreground "black"))))
     (w3m-anchor ((t (:foreground "cyan"))))
     (w3m-anchor-face ((t (:bold t :foreground "DodgerBlue1" :weight bold))))
     (w3m-arrived-anchor ((t (:foreground "magenta"))))
     (w3m-arrived-anchor-face ((t (:bold t :foreground "DodgerBlue3" :weight bold))))
     (w3m-bold ((t (:bold t :weight bold))))
     (w3m-current-anchor ((t (:bold t :underline t :weight bold))))
     (w3m-form-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-mouse ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (w3m-header-line-location-content ((t (:background "Gray20" :foreground "LightGoldenrod"))))
     (w3m-header-line-location-content-face ((t (:background "dark olive green" :foreground "wheat"))))
     (w3m-header-line-location-title ((t (:background "Gray20" :foreground "Cyan"))))
     (w3m-header-line-location-title-face ((t (:background "dark olive green" :foreground "beige"))))
     (w3m-history-current-url ((t (:background "SkyBlue4" :foreground "LightSkyBlue"))))
     (w3m-image ((t (:foreground "PaleGreen"))))
     (w3m-image-anchor ((t (:background "dark green"))))
     (w3m-insert ((t (:foreground "orchid"))))
     (w3m-italic ((t (:italic t :slant italic))))
     (w3m-strike-through ((t (:strike-through t))))
     (w3m-tab-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-mouse ((t (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected ((t (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-selected-retrieving ((t (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-retrieving ((t (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-unseen ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-underline ((t (:underline t))))
     (which-func ((t (:background "dark magenta" :foreground "yellow2"))))
     (white ((t (:foreground "white"))))
     (white-face ((t (:foreground "white"))))
     (white-red-face ((t (:background "red" :foreground "white"))))
     (widget ((t (:background "Gray80" :foreground "black"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition ((t (:foreground "yellow"))))
     (woman-addition-face ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "red" :weight bold))))
     (woman-bold-face ((t (:bold t :foreground "blue" :weight bold))))
     (woman-italic ((t (:italic t :foreground "green" :underline t :slant italic))))
     (woman-italic-face ((t (:italic t :foreground "red" :underline t :slant italic))))
     (woman-unknown ((t (:foreground "blue"))))
     (woman-unknown-face ((t (:foreground "brown"))))
     (wuxch-dired-avi-face ((t (:background "black" :foreground "yellow"))))
     (wuxch-dired-doc-face ((t (:background "red" :foreground "white"))))
     (wuxch-dired-elisp-face ((t (:background "black" :foreground "cyan"))))
     (wuxch-dired-exe-face ((t (:background "wheat" :foreground "darkorchid2"))))
     (x-face ((t (:background "white" :foreground "black"))))
     (x-symbol-adobe-fontspecific-face ((t (nil))))
     (x-symbol-face ((t (nil))))
     (x-symbol-heading-face ((t (:bold t :foreground "green4" :underline t :weight bold))))
     (x-symbol-info-face ((t (:foreground "green4"))))
     (x-symbol-invisible-face ((t (nil))))
     (x-symbol-revealed-face ((t (:background "pink"))))
     (xrdb-option-name-face ((t (:foreground "red"))))
     (xrdb-option-value-face ((t (:bold t :foreground "magenta" :weight bold))))
     (xref-error-face ((t (:foreground "red"))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "navy"))))
     (xsl-fo-alternate-face ((t (:foreground "Yellow"))))
     (xsl-fo-main-face ((t (:foreground "PaleGreen"))))
     (xsl-other-element-face ((t (:foreground "Coral"))))
     (xsl-xslt-alternate-face ((t (:foreground "LightGray"))))
     (xsl-xslt-main-face ((t (:foreground "Wheat"))))
     (xxml-emph-1-face ((t (:background "lightyellow"))))
     (xxml-emph-2-face ((t (:background "lightyellow"))))
     (xxml-header-1-face ((t (:background "seashell1" :foreground "MediumAquamarine"))))
     (xxml-header-2-face ((t (:background "seashell1" :foreground "SkyBlue"))))
     (xxml-header-3-face ((t (:background "seashell1"))))
     (xxml-header-4-face ((t (:background "seashell1"))))
     (xxml-interaction-face ((t (:background "lightcyan"))))
     (xxml-rug-face ((t (:background "cyan"))))
     (xxml-sparkle-face ((t (:background "yellow"))))
     (xxml-unbreakable-space-face ((t (:foreground "grey" :underline t))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yellow ((t (:foreground "yellow"))))
     (yellow-blue-face ((t (:background "blue" :foreground "yellow"))))
     (yellow-face ((t (:foreground "yellow"))))
     (yellow-forestgreen-face ((t (:background "forest green" :foreground "yellow"))))
     (yellow-red-face ((t (:background "red" :foreground "yellow"))))
     (zmacs-region ((t (:background "steelblue" :foreground "white")))))))

(color-theme-wdy)
(provide 'color-theme-wdy)